# Generated by Django 3.2.8 on 2022-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='buyer_state',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
